FROM debian

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y gcc libc6-dev vim sudo git

WORKDIR /home

# simple c programming env with gcc, main libs and vim

# build the image from the dockerfile
# docker build -t <name> .

# run the image created with appropriate flags
# docker run -it --rm <name>
