FROM alpine
RUN apk update && apk upgrade && apk add emacs
ENTRYPOINT emacs

# after vim, emacs...

# build the image from the dockerfile
# docker build -t <name> .

# run the image created with appropriate flags
# docker run -it --rm <name>
